#!/usr/bin/env ruby

# Charges all uncharged entrant

$: << "." << File.dirname(__FILE__)

require 'app'

Railscamp::Fifteen::Entrant.uncharged.all.each do |entrant|
  puts "charging #{entrant.id} #{entrant.email}"
  puts `#{File.dirname(__FILE__)}/charge #{entrant.id}`
end
