#!/usr/bin/env ruby

# swaps entrants

require 'pp'
$: << "." << File.dirname(__FILE__)

require 'app'

ep = ->(e) { "#{e.email} (#{e.id})" }

swap = ->(from_entrant_id, to_name, to_email) {
  from_entrant = Railscamp::Fifteen::Entrant[from_entrant_id]

  puts "from #{ep[from_entrant]}"

  ticket_type = 'swapped'
  notes = "swapped from #{ep[from_entrant]}"

  Railscamp::Fifteen::Entrant.create_without_cc!(to_name, to_email, ticket_type, notes)
  from_entrant.update(ticket_type:nil, notes: "swapped to #{to_email}")
}

#STDERR.puts Railscamp::Fifteen::EntrantCharger.new.charge!(entrant)
